version: '3'

services:
  # ddebian:
    # image: debian:buster-slim
    # volumes:
    #   - /root/Everything-42/transcendance/srcs/files/database:/datass
    # stdin_open: true
    # tty: true
    # # command: "/bin/bash && rm -rf datass"

  database:
    container_name: database
    image: postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - /root/Everything-42/transcendance/srcs/files/database:/var/lib/postgresql/data
    networks:
      - transcend-network

  backend:
    container_name: django
    build: /root/Everything-42/transcendance/srcs/files/backend/
    image: django
    ports:
      - "8000:8000"
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - back:/app/
    depends_on:
      - database
    networks:
      - transcend-network

  frontend:
    container_name: react
    build: /root/Everything-42/transcendance/srcs/files/frontend/
    image: react
    ports:
      - "5173:5173"
    env_file:
      - .env
    volumes:
      - front:/app/
    depends_on:
      - backend
    networks:
      - transcend-network

volumes:
  back:
      driver: local
      driver_opts:
         type: none
         device: /root/Everything-42/transcendance/srcs/files/backend/core/
         o: bind
  front:
    driver: local
    driver_opts:
      type: none
      device: /root/Everything-42/transcendance/srcs/files/frontend/core/
      o: bind
networks:
      transcend-network:
            name: transcend-network
            driver: bridge
  