# Generated by Django 5.0.2 on 2024-03-12 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0002_rename_date_tournament_creation_date_and_more'),
        ('users', '0002_user_avatar_participation'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='alias',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('busy', 'Busy'), ('away', 'Away'), ('available', 'Available')], default='available', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='tournament',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tournament.tournament'),
        ),
        migrations.DeleteModel(
            name='Participation',
        ),
    ]
