# Generated by Django 5.0.2 on 2024-05-28 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_blacklist_alter_user_friends'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='tournament',
        ),
    ]
