# Generated by Django 5.0.2 on 2024-03-24 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_alias_user_status_user_tournament_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='otp',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AddField(
            model_name='user',
            name='otp_expiry_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
