# Generated by Django 5.0.2 on 2024-03-28 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_otp_user_otp_expiry_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='two_factor',
            field=models.BooleanField(default=False),
        ),
    ]
