# Generated by Django 5.0.2 on 2024-05-31 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_tournament_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tournament_name',
            field=models.CharField(blank=True, max_length=7),
        ),
    ]
