# Generated by Django 5.0.2 on 2024-04-23 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_two_factor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='yoshi.jpg', upload_to='avatars/'),
        ),
    ]
