# Generated by Django 5.0.2 on 2024-05-10 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_friends_alter_user_avatar'),
        ('users', '0007_user_name'),
    ]

    operations = [
    ]
