# Generated by Django 5.0.2 on 2024-05-10 14:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_merge_20240510_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='blacklist',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
