# Generated by Django 5.0.2 on 2024-05-17 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=6, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('inprogress', 'In progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=255)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('max_capacity', models.IntegerField(default=2)),
            ],
        ),
    ]
