# Generated by Django 5.0.2 on 2024-04-23 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0002_rename_date_tournament_creation_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='winner',
        ),
        migrations.AddField(
            model_name='tournament',
            name='max_capacity',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='name',
            field=models.CharField(blank=True, max_length=6, unique=True),
        ),
    ]
