# Generated by Django 5.0.2 on 2024-06-10 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0004_alter_tournament_ball_starting_speed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='easyMode',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tournament',
            name='score',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='ball_starting_speed',
            field=models.FloatField(default=0.05),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='texture_ball',
            field=models.CharField(default='beaudibe.jpg'),
        ),
    ]
