# Generated by Django 5.0.2 on 2024-06-12 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0005_tournament_easymode_tournament_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='skin',
            field=models.IntegerField(default=2),
        ),
    ]
