# Generated by Django 5.0.2 on 2024-06-19 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0006_tournament_skin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='texture_ball',
            field=models.CharField(default='basketball.jpg'),
        ),
    ]
