# Generated by Django 5.0.2 on 2024-06-23 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0007_alter_tournament_texture_ball'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='creator',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
