# Generated by Django 5.0.2 on 2024-05-13 12:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_alter_messages_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 13, 14, 16, 43, 468569)),
        ),
    ]
