# Generated by Django 5.0.2 on 2024-04-23 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Room',
        ),
    ]
